CREATE TABLE [dbo].[Team]
(
	[PK_TeamID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [FK_Member1] INT NULL,
	[FK_Member2] INT NULL,
	[FK_Member3] INT NULL,
	[FK_Member4] INT NULL,
	[FK_Member5] INT NULL,
	[FK_Member6] INT NULL,
	[FK_Member7] INT NULL,
	[FK_Member8] INT NULL,
	[FK_Member9] INT NULL,
	[FK_Member10] INT NULL,
	CONSTRAINT [C_Member1] FOREIGN KEY ([FK_Member1]) REFERENCES [dbo].[User]([PK_UserID]),
	CONSTRAINT [C_Member2] FOREIGN KEY ([FK_Member2]) REFERENCES [dbo].[User]([PK_UserID]),
	CONSTRAINT [C_Member3] FOREIGN KEY ([FK_Member3]) REFERENCES [dbo].[User]([PK_UserID]),
	CONSTRAINT [C_Member4] FOREIGN KEY ([FK_Member4]) REFERENCES [dbo].[User]([PK_UserID]),
	CONSTRAINT [C_Member5] FOREIGN KEY ([FK_Member5]) REFERENCES [dbo].[User]([PK_UserID]),
	CONSTRAINT [C_Member6] FOREIGN KEY ([FK_Member6]) REFERENCES [dbo].[User]([PK_UserID]),
	CONSTRAINT [C_Member7] FOREIGN KEY ([FK_Member7]) REFERENCES [dbo].[User]([PK_UserID]),
	CONSTRAINT [C_Member8] FOREIGN KEY ([FK_Member8]) REFERENCES [dbo].[User]([PK_UserID]),
	CONSTRAINT [C_Member9] FOREIGN KEY ([FK_Member9]) REFERENCES [dbo].[User]([PK_UserID]),
	CONSTRAINT [C_Member20] FOREIGN KEY ([FK_Member10]) REFERENCES [dbo].[User]([PK_UserID]),
)
